# Generated by Django 3.0.4 on 2020-10-23 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import website.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.FileField(upload_to=website.models.user_directory_path)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('zipName', models.CharField(max_length=256)),
                ('complete', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserImageUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageName', models.CharField(max_length=256)),
                ('coordinateData', models.TextField()),
                ('saved', models.BooleanField(default=False)),
                ('count', models.IntegerField(default=0)),
                ('zipUpload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Upload')),
            ],
        ),
        migrations.CreateModel(
            name='SquareLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.CharField(max_length=256)),
                ('y', models.CharField(max_length=256)),
                ('w', models.CharField(max_length=256)),
                ('h', models.CharField(max_length=256)),
                ('classification', models.CharField(max_length=256)),
                ('color', models.CharField(max_length=256)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.UserImageUpload')),
            ],
        ),
        migrations.CreateModel(
            name='PointLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.CharField(max_length=256)),
                ('y', models.CharField(max_length=256)),
                ('dimension', models.CharField(max_length=256)),
                ('color', models.CharField(max_length=256)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.UserImageUpload')),
            ],
        ),
    ]
